### ISSUE TITLE
Django specific?

### ISSUE THREAD

**Issue by mythmon** [mozilla-services/python-dockerflow#1]
The code I see here seems very Django specific. I'm ok with this, but it is in contrast with the name of the package, `python-dockerflow`. Is the goal of this package to be generic across any Python app? Or should we rename the repo to `django-dockerflow`?

**Comment by jezdez** [comment]
Yep, the code is currently Django specific since that's what was existing when I started to port it. That's why the Django support is in ``dockerflow.django``.

The plan is to have a central repo for various Python bits, e.g. a Flask extension in `dockerflow.flask` is next on my TODO list for Re:dash/Airflow. The general idea is to keep the code in one repo to be able to implement the core pieces centrally instead of individually per Python-based framework/toolset.

Alternatively we could have made python-dockerflow only implement the core features (e.g. "get content of version.json from a location") and then have separate packages per framework/toolset (e.g. django-dockerflow, flask-dockerflow, pyramid-dockerflow). I decided against that since it increases the amount of maintenance burden dramatically at the stage, and we can still do that split if really needed at a later stage.

**Comment by jezdez** [comment]
Closing this as I think it's not an issue, please do reopen if you want to do the split right away.

**Comment by mythmon** [comment]
I think having this all in one repo makes sense. I just wanted to clarify what the intentions were.

**Comment by jezdez** [comment]
@mythmon \o/
