### ISSUE TITLE
Constructor of formatter should be (fmt, datefmt, style)

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/python-dockerflow#24]
Currently the `style` parameter is used as `logger_name`.

Because of this, when the formatter is initialized from `.ini` files, the `Logger` field is set to `%`:
https://github.com/python/cpython/blob/97d7e65dfed1d42d40d9bc2f630af56240555f02/Lib/logging/config.py#L112-L119

Maybe, the constructor signature could be:
```py
def __init__(self, fmt=None, datefmt=None, style='%', logger_name='Dockerflow'):
    ...
```

(From https://github.com/mozilla/mozilla-cloud-services-logger/issues/3)

**Comment by jezdez** [comment]
Meh, the Formatter class only got the style argument in 3.1, so it would at least be a leaky compatibility with your suggested signature.

What strikes me as odd is that the ini based logger code doesn't allow for additional paramters like the dict based logging setup: https://github.com/python/cpython/blob/97d7e65dfed1d42d40d9bc2f630af56240555f02/Lib/logging/config.py#L463-L464

I guess we can still use your signature though since the `dictConfig` code path uses keyword arguments that would correctly work.
