### ISSUE TITLE
Should dockerflow heartbeat fail on warnings?

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/python-dockerflow#47]
While using dockerflow, the `__heartbeat__` view fails if any checks throw a message of `checks.messages.WARNING` or higher. Should it fail on `WARNING`s, or only fail on `ERROR` or `CRITICAL` messages?

**Comment by jezdez** [comment]
I think this code was ported from Django's system checks, can you check if this is true there as well?

**Comment by groovecoder** [comment]
The `BaseCommand` `check` method has a `fail_level=checks.ERROR` parameter default:

https://github.com/django/django/blob/c60524c658f197f645b638f9bcc553103bfe2630/django/core/management/base.py#L406-L414

**Comment by groovecoder** [comment]
The only way to override the `fail_level=checks.ERROR` default is with a command-line argument to a management command, or configuring a custom `fail_level` in an app registry.

**Comment by jezdez** [comment]
Yeah, I think we should just update https://github.com/mozilla-services/python-dockerflow/blob/d7fadb7380798bb8d1df5e50b84bf9defdedf5aa/src/dockerflow/django/views.py#L60 to use `checks.messages.ERROR`. Also, since the Flask and Sanic integration has similar things, we need to be consistent and update it there, too.

**Comment by groovecoder** [comment]
Submitted https://github.com/mozilla-services/python-dockerflow/pull/49
